*** empty log message ***

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1620,8 +1620,9 @@ Optional Packages:
   --with-qt-includes=DIR  where the Qt includes are.
   --with-qt-libraries=DIR where the Qt library is installed.
   --without-arts          build without aRts default=yes
-  --with-gc         use garbage collector
-  --with-malloc-debug         use MallocDebug.app
+  --without-nidaqmx		build without NIDAQmx default=yes
+  --with-gc		use garbage collector
+  --with-malloc-debug	use MallocDebug.app
 
 Some influential environment variables:
   CC          C compiler command
@@ -8047,7 +8048,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 8050 "configure"' > conftest.$ac_ext
+  echo '#line 8051 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -9892,11 +9893,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9895: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9896: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:9899: \$? = $ac_status" >&5
+   echo "$as_me:9900: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -10124,11 +10125,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10127: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10128: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:10131: \$? = $ac_status" >&5
+   echo "$as_me:10132: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -10191,11 +10192,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10194: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10195: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:10198: \$? = $ac_status" >&5
+   echo "$as_me:10199: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12430,7 +12431,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12433 "configure"
+#line 12434 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12528,7 +12529,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12531 "configure"
+#line 12532 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14739,11 +14740,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14742: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14743: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14746: \$? = $ac_status" >&5
+   echo "$as_me:14747: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -14806,11 +14807,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14809: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14810: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14813: \$? = $ac_status" >&5
+   echo "$as_me:14814: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16214,7 +16215,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 16217 "configure"
+#line 16218 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -16312,7 +16313,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 16315 "configure"
+#line 16316 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -17137,11 +17138,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17140: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17141: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17144: \$? = $ac_status" >&5
+   echo "$as_me:17145: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -17204,11 +17205,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17207: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17208: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17211: \$? = $ac_status" >&5
+   echo "$as_me:17212: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -19210,11 +19211,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19213: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19214: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:19217: \$? = $ac_status" >&5
+   echo "$as_me:19218: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -19442,11 +19443,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19445: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19446: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:19449: \$? = $ac_status" >&5
+   echo "$as_me:19450: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -19509,11 +19510,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19512: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19513: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:19516: \$? = $ac_status" >&5
+   echo "$as_me:19517: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -21748,7 +21749,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 21751 "configure"
+#line 21752 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -21846,7 +21847,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 21849 "configure"
+#line 21850 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -31025,7 +31026,7 @@ for i in $jpeg_incdirs;
 do
   for j in jpeglib.h;
   do
-    echo "configure: 31028: $i/$j" >&5
+    echo "configure: 31029: $i/$j" >&5
     if test -r "$i/$j"; then
       echo "taking that" >&5
       jpeg_incdir=$i
@@ -31330,7 +31331,7 @@ for i in $qt_incdirs;
 do
   for j in $kde_qt_header;
   do
-    echo "configure: 31333: $i/$j" >&5
+    echo "configure: 31334: $i/$j" >&5
     if test -r "$i/$j"; then
       echo "taking that" >&5
       qt_incdir=$i
@@ -32170,7 +32171,7 @@ for i in $kde_incdirs;
 do
   for j in $kde_check_header;
   do
-    echo "configure: 32173: $i/$j" >&5
+    echo "configure: 32174: $i/$j" >&5
     if test -r "$i/$j"; then
       echo "taking that" >&5
       kde_incdir=$i
@@ -32200,7 +32201,7 @@ for i in $kde_libdirs;
 do
   for j in $kde_check_lib;
   do
-    echo "configure: 32203: $i/$j" >&5
+    echo "configure: 32204: $i/$j" >&5
     if test -r "$i/$j"; then
       echo "taking that" >&5
       kde_libdir=$i
@@ -32218,7 +32219,7 @@ for i in $kde_libdirs;
 do
   for j in "kde3/plugins/designer/kdewidgets.la";
   do
-    echo "configure: 32221: $i/$j" >&5
+    echo "configure: 32222: $i/$j" >&5
     if test -r "$i/$j"; then
       echo "taking that" >&5
       kde_widgetdir=$i
@@ -33664,7 +33665,7 @@ for i in $kde_sharedirs;
 do
   for j in apps/ksgmltools2/customization/kde-chunk.xsl;
   do
-    echo "configure: 33667: $i/$j" >&5
+    echo "configure: 33668: $i/$j" >&5
     if test -r "$i/$j"; then
       echo "taking that" >&5
       KDE_XSL_STYLESHEET=$i
@@ -34035,22 +34036,192 @@ RUBY_LIBS="$RUBY_LIBS $ruby_libs"
 RUBY_CFLAGS="$RUBY_CFLAGS $ruby_cflags"
 LIBS="$ac_save_LIBS"
 
-{ echo "$as_me:$LINENO: checking for NI-DAQmx" >&5
-echo $ECHO_N "checking for NI-DAQmx... $ECHO_C" >&6; }
-if test -f /usr/local/lib/libnidaqmx.so ; then
-  { echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6; }
+
+# Check whether --with-nidaqmx was given.
+if test "${with_nidaqmx+set}" = set; then
+  withval=$with_nidaqmx; if test "$with_nidaqmx" = "yes"; then
+	ac_save_LIBS="$LIBS"
+	{ echo "$as_me:$LINENO: checking for main in -lnidaqmx" >&5
+echo $ECHO_N "checking for main in -lnidaqmx... $ECHO_C" >&6; }
+if test "${ac_cv_lib_nidaqmx_main+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lnidaqmx -L/usr/local/lib -lnidaqmx $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+return main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag" || test ! -s conftest.err'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_nidaqmx_main=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_nidaqmx_main=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_nidaqmx_main" >&5
+echo "${ECHO_T}$ac_cv_lib_nidaqmx_main" >&6; }
+if test $ac_cv_lib_nidaqmx_main = yes; then
+  nidaqmx_libs="-L/usr/local/lib -lnidaqmx"\
+	nidaqmx_cflags="-I/usr/local/include"
 
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_NI_DAQMX 1
 _ACEOF
 
-  NIDAQMX_LIBS="-L/usr/local/lib -lnidaqmx"
-  NIDAQMX_CFLAGS="-I/usr/local/include"
 else
-  { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
+  { { echo "$as_me:$LINENO: error: NIDAQmx is not installed - NIDAQmx is disabled" >&5
+echo "$as_me: error: NIDAQmx is not installed - NIDAQmx is disabled" >&2;}
+   { (exit 1); exit 1; }; }
 fi
+
+	NIDAQMX_LIBS="$nidaqmx_libs"
+	NIDAQMX_CFLAGS="$nidaqmx_cflags"
+	LIBS="$ac_save_LIBS"
+fi
+else
+  ac_save_LIBS="$LIBS"
+	{ echo "$as_me:$LINENO: checking for main in -lnidaqmx" >&5
+echo $ECHO_N "checking for main in -lnidaqmx... $ECHO_C" >&6; }
+if test "${ac_cv_lib_nidaqmx_main+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lnidaqmx -L/usr/local/lib -lnidaqmx $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+return main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag" || test ! -s conftest.err'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_nidaqmx_main=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_nidaqmx_main=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_nidaqmx_main" >&5
+echo "${ECHO_T}$ac_cv_lib_nidaqmx_main" >&6; }
+if test $ac_cv_lib_nidaqmx_main = yes; then
+  nidaqmx_libs="-L/usr/local/lib -lnidaqmx"\
+	nidaqmx_cflags="-I/usr/local/include"
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_NI_DAQMX 1
+_ACEOF
+
+else
+  { echo "$as_me:$LINENO: WARNING: NIDAQmx is not installed - NIDAQmx is disabled" >&5
+echo "$as_me: WARNING: NIDAQmx is not installed - NIDAQmx is disabled" >&2;}
+fi
+
+	NIDAQMX_LIBS="$nidaqmx_libs"
+	NIDAQMX_CFLAGS="$nidaqmx_cflags"
+	LIBS="$ac_save_LIBS"
+
+fi
+
 
 { echo "$as_me:$LINENO: checking for main in -lcomedilib" >&5
 echo $ECHO_N "checking for main in -lcomedilib... $ECHO_C" >&6; }
@@ -34225,7 +34396,8 @@ LINUXGPIB_LIBS="$gpib_libs"
 
 # Check whether --with-gc was given.
 if test "${with_gc+set}" = set; then
-  withval=$with_gc; ac_save_LIBS="$LIBS"
+  withval=$with_gc; if test "$with_gc" = "yes"; then
+	ac_save_LIBS="$LIBS"
 	{ echo "$as_me:$LINENO: checking for main in -lgccpp" >&5
 echo $ECHO_N "checking for main in -lgccpp... $ECHO_C" >&6; }
 if test "${ac_cv_lib_gccpp_main+set}" = set; then
@@ -34311,6 +34483,7 @@ fi
 
 	GC_LIBS="$GC_LIBS $gc_libs"
 	LIBS="$ac_save_LIBS"
+fi
 
 fi
 
@@ -34318,7 +34491,8 @@ fi
 
 # Check whether --with-malloc-debug was given.
 if test "${with_malloc_debug+set}" = set; then
-  withval=$with_malloc_debug; ac_save_LIBS="$LIBS"
+  withval=$with_malloc_debug; if test "$with_malloc_debug" = "yes"; then
+	ac_save_LIBS="$LIBS"
 	{ echo "$as_me:$LINENO: checking for main in -lMallocDebug" >&5
 echo $ECHO_N "checking for main in -lMallocDebug... $ECHO_C" >&6; }
 if test "${ac_cv_lib_MallocDebug_main+set}" = set; then
@@ -34404,6 +34578,7 @@ fi
 
 	MALLOC_DEBUG_LIBS="$MALLOC_DEBUG_LIBS $malloc_debug_libs"
 	LIBS="$ac_save_LIBS"
+fi
 
 fi
 
@@ -37708,7 +37883,7 @@ _ACEOF
 
 
 
-CPPFLAGS="$CPPFLAGS $RUBY_CFLAGS $FREETYPE2_CFLAGS"
+CPPFLAGS="$CPPFLAGS $RUBY_CFLAGS $FREETYPE2_CFLAGS $NIDAQMX_CFLAGS"
 
 
 DO_NOT_COMPILE="$DO_NOT_COMPILE CVS debian bsd-port admin"
